### PR TITLE
Add support for the most used locales

### LINKED ISSUE #45: Support more locales than just `en-US`

### PR DESCRIPTION
**Pull request by bloussou**
close #45
related to https://github.com/atoti/atoti/issues/451

### CODE REVIEW

**Comment by tibdex** [comment]
On `main`:
Screen Shot 2022-01-20 at 11 37 45
On this branch:
Screen Shot 2022-01-20 at 11 37 29

This big size bump is probably not worth it. Can we instead use [this list](https://stackoverflow.com/a/9713377/5558141):

- `bn-IN`
- `da-DK`
- `de-DE`
- `en-US`
- `en-GB`
- `es-ES`
- `es-MX`
- `fr-FR`
- `it-IT`
- `ja-JP`
- `pt-BR`
- `ru-RU`
- `zh-CN`

**Comment by bloussou** [comment]
image

**Review by tibdex — APPROVED** [review]

**Review by fabiencelier — COMMENTED** [review]
✅

**Comment by tibdex** [comment]
Thank you for the timely review Fabich.

**Pull request merged**
